### ISSUE TITLE
22/4/20 打卡无法运行，出现报错：Remote end closed connection without response

### ISSUE THREAD

**Issue by Sakiyary** [kottory/NJU-health-report#22]
疑似503？要是有老哥来解决一下就好了

**Comment by Sakiyary** [comment]
我是13:00定时运行脚本的，有同学说12:00还好好的

**Comment by Sakiyary** [comment]
![UL`1YT8C(4BI%FV~J`})J$V](https://user-images.githubusercontent.com/60864459/164164527-1dacd6b3-f848-472b-a35c-f300e665117b.png)
补充报错截图

**Comment by LuZhuanz** [comment]
相同的问题

**Comment by cmj2002** [comment]
在 Actions 和本地运行时均成功复现此问题，本地运行是在校园网内，应该不是基于 IP 的封锁。

APP 打卡仍然正常（没有更新APP），怀疑是基于 Request Header 的封锁？

附错误输出：

```
2022-04-20 14:36:27,282 root         INFO     尝试登录...
2022-04-20 14:36:27,286 root         INFO     统一认证平台需要输入验证码才能继续，尝试识别验证码...
2022-04-20 14:36:27,819 root         INFO     登录成功！
2022-04-20 14:36:27,819 root         INFO     尝试获取打卡列表信息...
2022-04-20 14:36:27,920 root         INFO     正在打卡
Traceback (most recent call last):
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cmj/Desktop/自动打卡/run.py", line 80, in <module>
    auth.session.get(url)
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/cmj/Desktop/自动打卡/venv/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by Sakiyary** [comment]
看起来是服务器不稳定/维护导致，现在可以运行脚本了，应该可以在`.github/workflow/report.yml`中多设定几个schedule进行多次打卡？

**Comment by cmj2002** [comment]
确实，恢复了，白抓包了😂

**Comment by Stephenluoyi** [comment]
现在好像又不行了？

**Comment by EKiritsugu** [comment]
问题似乎仍然存在，今天在下午和晚上重复实验了多次，都无法运行。

**Comment by Roc136** [comment]
尝试在session中修改Headers如下：
```json
{
  "Host": "ehallapp.nju.edu.cn",
  "Connection": "keep-alive",
  "Accept": "application/json, text/plain, */*",
  "User-Agent": $UA,
  "X-Requested-With": "com.wisedu.cpdaily.nju",
  "Referer": "http://ehallapp.nju.edu.cn/xgfw/sys/mrjkdkappnju/index.html",
  "Accept-Encoding": "gzip, deflate",
  "Accept-Language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"
}
```
以上是App中的信息，替换UA为自己的UA或使用随机UA

**Comment by kottory** [comment]
没错，我这边也发现了是referer的问题。一会儿改一下。

不得不说这个脚本因为刚开始觉得不太可能会变动所以写得很丑，没想到一周之内修了好几次。。

打算把一些写的很丑的地方改写一下，然后加一些注释。

**Comment by kottory** [comment]
已修复。如果明天能够正常使用的话我就关掉这个issue了…

**Comment by Stephenluoyi** [comment]
还是有问题
![image](https://user-images.githubusercontent.com/60831199/164363887-17035723-2de6-417f-92f9-6281a1165991.png)

**Comment by kottory** [comment]
这个是我单纯实现问题…我一会儿改一下。
不影响使用的，你这个应该也是打卡成功了。

**Comment by kottory** [comment]
好像是新问题，可以正常申请打卡但是不会成功申请。

**Comment by Stephenluoyi** [comment]
是不是学校系统的问题，我app上自己手动打卡也出bug了，填完提交之后还显示未填报

**Comment by psn417** [comment]
测试了一下应该是请求头有问题
"Referer": "http://ehallapp.nju.edu.cn/xgfw/sys/mrjkdkappnju/index.html"
"User-Agent": "Mozilla/5.0 (Linux; Android 11; M2006J10C Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.131 Mobile Safari/537.36  cpdaily/8.2.7 wisedu/8.2.7"
改了这两个请求头就能打卡成功了

referer写错会无响应
UA写错则会提示“请在南京大学APP中使用当前应用服务”
UA必须包含 cpdaily 这个字符串，别的都能去掉

**Comment by JlxxXU** [comment]
> 测试了一下应该是请求头有问题 "Referer": "http://ehallapp.nju.edu.cn/xgfw/sys/mrjkdkappnju/index.html" "User-Agent": "Mozilla/5.0 (Linux; Android 11; M2006J10C Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.131 Mobile Safari/537.36 cpdaily/8.2.7 wisedu/8.2.7" 改了这两个请求头就能打卡成功了
> 
> referer写错会无响应 UA写错则会提示“请在南京大学APP中使用当前应用服务” UA必须包含 cpdaily 这个字符串，别的都能去掉

那为什么之前正常呢，真诚发问

**Comment by psn417** [comment]
> > 测试了一下应该是请求头有问题 "Referer": "http://ehallapp.nju.edu.cn/xgfw/sys/mrjkdkappnju/index.html" "User-Agent": "Mozilla/5.0 (Linux; Android 11; M2006J10C Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.131 Mobile Safari/537.36 cpdaily/8.2.7 wisedu/8.2.7" 改了这两个请求头就能打卡成功了
> > referer写错会无响应 UA写错则会提示“请在南京大学APP中使用当前应用服务” UA必须包含 cpdaily 这个字符串，别的都能去掉
> 
> 那为什么之前正常呢，真诚发问

可能是服务器为了反脚本加了检测？
