### ISSUE TITLE
连续十次打卡失败

### ISSUE THREAD

**Issue by myandeg** [kottory/NJU-health-report#26]
连续十次打卡失败后退出

本地运行：
```
2022-04-21 11:12:50,789 INFO     尝试登录...
2022-04-21 11:12:50,798 INFO     统一认证平台需要输入验证码才能继续，尝试识别验证码...
2022-04-21 11:12:51,074 INFO     登录成功！
2022-04-21 11:12:51,074 INFO     尝试获取打卡列表信息...
2022-04-21 11:12:51,190 INFO     正在打卡
2022-04-21 11:12:52,194 INFO     尝试获取打卡列表信息...
2022-04-21 11:12:52,214 INFO     正在打卡
2022-04-21 11:12:53,221 INFO     尝试获取打卡列表信息...
2022-04-21 11:12:53,242 INFO     正在打卡
2022-04-21 11:12:54,251 INFO     尝试获取打卡列表信息...
2022-04-21 11:12:54,274 INFO     正在打卡
2022-04-21 11:12:55,284 INFO     尝试获取打卡列表信息...
2022-04-21 11:12:55,307 INFO     正在打卡
2022-04-21 11:12:56,320 INFO     尝试获取打卡列表信息...
2022-04-21 11:12:56,341 INFO     正在打卡
2022-04-21 11:12:57,350 INFO     尝试获取打卡列表信息...
2022-04-21 11:12:57,372 INFO     正在打卡
2022-04-21 11:12:58,382 INFO     尝试获取打卡列表信息...
2022-04-21 11:12:58,419 INFO     正在打卡
2022-04-21 11:12:59,429 INFO     尝试获取打卡列表信息...
2022-04-21 11:12:59,454 INFO     正在打卡
2022-04-21 11:13:00,464 INFO     尝试获取打卡列表信息...
2022-04-21 11:13:00,490 INFO     正在打卡
2022-04-21 11:13:01,500 ERROR    打卡失败，请尝试手动打卡
Traceback (most recent call last):
  File "/home/myandeg/github/NJU-health-report/run.py", line 58, in <module>
    os.exit(-1)
AttributeError: module 'os' has no attribute 'exit'
```

GitHub Actions
```
Run python run.py
  python run.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.12/x64/lib
    NJU_USERNAME: ***
    NJU_PASSWORD: ***
    CURR_LOCATION: ***
2022-04-21 03:35:48,403 INFO     尝试登录...
2022-04-21 03:35:48,621 INFO     统一认证平台需要输入验证码才能继续，尝试识别验证码...
2022-04-21 03:35:49,738 INFO     登录成功！
2022-04-21 03:35:49,738 INFO     尝试获取打卡列表信息...
2022-04-21 03:35:51,549 INFO     正在打卡
2022-04-21 03:35:52,770 INFO     尝试获取打卡列表信息...
2022-04-21 03:35:54,296 INFO     正在打卡
2022-04-21 03:35:55,515 INFO     尝试获取打卡列表信息...
2022-04-21 03:35:55,962 INFO     正在打卡
2022-04-21 03:35:57,181 INFO     尝试获取打卡列表信息...
2022-04-21 03:35:57,632 INFO     正在打卡
2022-04-21 03:35:58,851 INFO     尝试获取打卡列表信息...
2022-04-21 03:35:59,300 INFO     正在打卡
2022-04-21 03:36:00,519 INFO     尝试获取打卡列表信息...
2022-04-21 03:36:00,997 INFO     正在打卡
2022-04-21 03:36:02,216 INFO     尝试获取打卡列表信息...
2022-04-21 03:36:02,682 INFO     正在打卡
2022-04-21 03:36:03,900 INFO     尝试获取打卡列表信息...
2022-04-21 03:36:04,353 INFO     正在打卡
2022-04-21 03:36:05,572 INFO     尝试获取打卡列表信息...
2022-04-21 03:36:06,019 INFO     正在打卡
2022-04-21 03:36:07,239 INFO     尝试获取打卡列表信息...
2022-04-21 03:36:07,690 INFO     正在打卡
2022-04-21 03:36:08,915 ERROR    打卡失败，请尝试手动打卡
Traceback (most recent call last):
  File "/home/runner/work/NJU-health-report/NJU-health-report/run.py", line 58, in <module>
    os.exit(-1)
AttributeError: module 'os' has no attribute 'exit'
```

**Comment by myandeg** [comment]
不是脚本问题，发现我手动打卡同样失败了

**Comment by cmj2002** [comment]
我觉得应该还是脚本的问题，我在下午两点半左右尝试自动打卡，出现同样的问题，但是手动打卡可以成功，获取列表信息为已填报

**Comment by cmj2002** [comment]
用[Issue 22](https://github.com/kottory/NJU-health-report/issues/22#issuecomment-1104719642)中的方法解决了这个问题
